version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: master_ip_db
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: masterpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./start.sh
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://masteruser:masterpass@db:5432/master_ip_db
      ROOT_PATH: ""
    ports:
      - "8000:8000"
    # volume removed to prevent static files from being overridden in production

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - web
    networks:
      - default

volumes:
  postgres_data:
