version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: master_ip_cloud
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: masterpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: ./start.sh
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://masteruser:masterpass@db:5432/master_ip_cloud
      APP_ROLE: cloud
    ports:
      - "8000:8000"
volumes:
  postgres_data:
