version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: master_ip_cloud
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: masterpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  app:
    build:
      context: ../..
    command: ./start.sh
    env_file:
      - .env.cloud
    depends_on:
      - db
    volumes:
      - ../../alembic:/app/alembic
      - logs:/app/logs
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ../../nginx/cloud.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app

volumes:
  postgres_data:
  logs:
