version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: master_ip_db
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: masterpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ../..
    command: ./start.sh
    env_file:
      - .env.local
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
