apiVersion: v1
kind: ConfigMap
metadata:
  name: master-ip-config
  namespace: master-ip
data:
  ROLE: "local"
  DATABASE_URL: "postgresql://masteruser:masterpass@postgres:5432/master_ip_db"
  ENABLE_BACKGROUND_WORKERS: "1"
  ENABLE_CLOUD_SYNC: "1"
  ENABLE_SYNC_PUSH_WORKER: "1"
  ENABLE_SYNC_PULL_WORKER: "1"
