apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-ip-db
  namespace: master-ip
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: master_ip_db
        - name: POSTGRES_USER
          value: masteruser
        - name: POSTGRES_PASSWORD
          value: masterpass
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: master-ip
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
